### ISSUE TITLE
I don't know how to use the library

### ISSUE THREAD

**Issue by ghost** [digama0/dae-parser#1]
Please write clear documentation!!!

**Comment by digama0** [comment]
This is not an actionable comment. What is it that you want to do? The entry point is the `Document` type, and you can use it to either read or write files in the collada format. The types closely mirror the [collada spec](https://www.khronos.org/files/collada_spec_1_4.pdf), so you may need to consult the collada documentation or look at some blender files to decide how to store data.

**Comment by ghost** [comment]
All the library does is just read the file?I can read the file and using the standard library std::io. I was hoping this library would output the size, position, etc. of the object from the collade to a variable instead of just reading it...

**Comment by digama0** [comment]
It parses and validates the object against the collada specification. You can access the size, position, etc of the object via the relevant fields, e.g. the [`Transform`](https://docs.rs/dae-parser/latest/dae_parser/enum.Transform.html) on a [`Node`](https://docs.rs/dae-parser/latest/dae_parser/struct.Node.html) or the [`Node::transform_as_matrix()`](https://docs.rs/dae-parser/latest/src/dae_parser/core/scene.rs.html#311-316) function (which unfortunately doesn't show up in docs.rs because it requires the nalgebra feature flag).

Note that features are driven by users and while this crate has been used to implement a reasonably featureful 3D model viewer (so it's not completely off-base), unless people try to use it and make concrete suggestions for improvement nothing will change here, since it's already serving its purpose as far as I am concerned.

**Comment by ghost** [comment]
I understand you, but I doubt that if you just give a piece of code in the README file, the community will understand everything and they will support the library. I, as a person who wants to use and support the library, wants to understand its use more.
I mean give a more understandable code with comments for each action. For example:
`//Get object's size`
`let size = document.get_size();`
`println!("Object size is {}", size);`

**Comment by digama0** [comment]
That's probably true, but I have no idea what the usage code looks like outside my narrow application domain. I don't even know what you mean by object size in that code snippet - that function certainly doesn't exist. The main things you can do with a document are: find the main scene, loop over all the `*_library` objects of a given type or set of types, find an object of some type by ID. Those are operations that actually have something to do with the structure of the data as it exists. "Object size" isn't really a thing.

Maybe it's just an example, but actually making use of a model file through little operations like this seems quite difficult. The code example in the readme is the smallest fully self contained example I could come up with that isn't entirely trivial (e.g. a file with no objects). But there are a huge number of different types and different use cases go in different directions, so I wouldn't know where to start. Hence the request for actionable feedback.
