### ISSUE TITLE
Parsing dae file with comments

### ISSUE THREAD

**Issue by EtaLoop** [digama0/dae-parser#3]
### WHAT
While parsing valid collada 1.4.1 document, adding a comment make program return an error : 
`Error while loading from str: Minidom(NoComments)`

Maybe we want the comment to be ignored during parsing or to be stored somewhere.

**Comment by digama0** [comment]
I think this needs to be reported upstream on minidom, I don't know why comments are rejected in this way.

...Unfortunately since I had to fork minidom I guess that's also on me. What is upstream doing about this?

Seems minidom switched to `rxml`, which [also does not allow comments](https://codeberg.org/jssfr/rxml/src/branch/main/rxml/README.md#features-some-call-them-restrictions), but it is being used in a project that is doing XMPP parsing so the constraints are a bit different. I don't know if collada 1.4.1 allows comments. (EDIT: It does.)

**Comment by digama0** [comment]
Fixed in [v0.11](https://github.com/digama0/dae-parser/commit/5784e61075befa95882bb98158b049c9cfd374c3) via [`minidom-14/8a06a60`](https://github.com/digama0/minidom-14/commit/8a06a6090e3dd1c9c0f5979ff1f6d5e6bf3b4377)

**Comment by digama0** [comment]
The implementation here just ignores comments, and never writes them. I don't think the collada spec uses comments for data storage, so hopefully this is fine; otherwise you can open a new issue and describe your use case if you need comment writing or preservation.

**Comment by EtaLoop** [comment]
Thanks !
